#Ctrl-h → split horizontally
bind-key -n C-n split-window -h

# Ctrl-\ → split vertically
bind-key -n C-\\ split-window -v

# Ctrl-x → close current pane
bind-key -n C-x kill-pane


# ────────────── Vim-style pane navigation ──────────────
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-h select-pane -L
bind-key -n C-l select-pane -R
